# Generated by Django 5.0 on 2024-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="temperament",
            field=models.CharField(
                choices=[
                    ("calm", "Calm"),
                    ("energetic", "Energetic"),
                    ("aggressive", "Aggressive"),
                ],
                default="calm",
                max_length=10,
            ),
        ),
    ]
