# Generated by Django 5.0 on 2024-05-27 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0003_adoptionapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
