# Generated by Django 5.0 on 2024-05-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0004_dog_created_at_dog_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
