# Generated by Django 5.0 on 2024-05-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="save",
            options={"verbose_name": "Favorite", "verbose_name_plural": "Favotites"},
        ),
    ]
